# Generated by Django 6.0.1 on 2026-01-31 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='titulo',
            field=models.CharField(verbose_name='Titulo do link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(verbose_name='URL do link'),
        ),
    ]
